name: delete

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      GH_TOKEN:
        description: token with admin repo privilege
        required: false
      GH_APP_ID:
        description: App id with admin privilege
        required: false
      GH_PRIVATE_KEY:
        description: App private key with admin privilege
        required: false

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download ssh key
        uses: actions/download-artifact@v3
        with:
          name: ssh
          path: ~/.ssh
      - name: Set ssh key permission
        run: chmod 400 ~/.ssh/id_rsa
      - name: login to azure
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      - name: Get workflow repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/azure-runner
          path: workflow-repo
      - name: Fix script permissions
        run: |
          sudo apt-get install -y dos2unix
          dos2unix workflow-repo/main.sh
          dos2unix workflow-repo/setup.sh.template
          chmod +x workflow-repo/main.sh
      - name: Display VM Info
        run: |
          echo "Deleting VM: github-runner${RUN_ID}vm"
      - name: run script
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: bash ./workflow-repo/main.sh --destroy 